spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}  # You can use 'validate', 'create', or 'none' based on your needs
    show-sql: true  # This will print SQL queries to the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
